version: '3'
services:
  erddap:
    image: axiom/docker-erddap
    ports:
    - 8080:8080
    volumes:
    - ./content/erddap-dev:/usr/local/tomcat/content/erddap
    - ./kiatest:/erddapData
    - ./raw:/raw
    - ${PWD}/config/web.xml:/usr/local/tomcat/webapps/erddap/WEB-INF/web.xml
