version: '3'
services:
  erddap:
    image: axiom/docker-erddap
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - ./content/erddap:/usr/local/tomcat/content/erddap
    - /isilon_erddap/kiatest:/erddapData
